* pii_surfaces_summary.do -- TEMPLATE: how much sits on each non-value PII surface, per dataset.
* Set the four globals below (or `do` a config file that sets them) and run.
*   $DATADIR  folder holding the datasets      $DTALIST  text file, one dataset path per line
*   $OUTDIR   where the CSVs go                $CODEDIR  the package's do-files (to test whether notes are read)
* Surfaces (references/pii-surfaces.md): B1 value labels (sets/entries; entries with a
* direct-identifier term or > 40 chars), B2/B3 variable labels with a direct term, B4 dataset
* label / notes / characteristics (counts, size, full text exported; machine-generated
* reshape/xi/tsset characteristics told apart), C4 embedded file paths; plus whether any
* do-file reads notes or characteristics (if none does, they can go without touching code).
* Outputs: pii_surfaces_summary.csv (one row per dataset), dataset_notes.csv (every note and
* characteristic, full text), value_label_flags.csv (flagged label entries).
* Needs _surf_vlabel.ado on the adopath (its Mata helper is loaded with `run` below).
findfile _surf_vlabel.ado
run "`r(fn)'"                                  // defines the Mata helper _surf_vlabel_m()
local DIRECT "name|dob|birth|address|phone|contact|mobile|cnic|national id|email|caste|gps|latitude|longitude"
* --- does any do-file read notes or characteristics? (helper script, read-only) ---
!find "$CODEDIR" -name "*.do" -not -path "*/ado/*" -print0 | xargs -0 grep -lE "^[[:space:]]*(notes?([[:space:]]+(list|search))?[[:space:]]*$|notes?[[:space:]]+(list|search)[[:space:]]|char[[:space:]]+(list|dir)|_dta\[)" > "$OUTDIR/notes_readers.txt" 2>/dev/null; true
tempname S N L
file open `S' using "$OUTDIR/pii_surfaces_summary.csv", write replace
file write `S' "dataset,dataset_label,n_variables,n_string_vars,n_notes,notes_total_chars,n_char_entries,n_value_label_sets,n_value_label_entries,n_value_label_entries_flagged,n_var_labels_with_direct_term,n_labels_or_notes_with_path" _n
file open `N' using "$OUTDIR/dataset_notes.csv", write replace
file write `N' "dataset,kind,name,number,text" _n
file open `L' using "$OUTDIR/value_label_flags.csv", write replace
file write `L' "dataset,value_label,value,label_text,why" _n
file open IN using "$DTALIST", read text
file read IN line
while r(eof)==0 {
    local rel "`line'"
    quietly use "$DATADIR/`rel'", clear
    local dlab : data label
    mata: st_local("dlab", subinstr(subinstr(subinstr(subinstr(st_local("dlab"), char(96), "'"), char(34), "'"), ",", ";"), char(39), uchar(8217)))
    quietly ds
    local nv : word count `r(varlist)'
    quietly ds, has(type string)
    local ns : word count `r(varlist)'
    * ---- notes (dataset and variable) ----
    local nnotes = 0
    local nchars = 0
    local npath = 0
    local nn : char _dta[note0]
    if "`nn'"=="" local nn = 0
    forvalues i = 1/`nn' {
        local t : char _dta[note`i']
        mata: st_local("t", subinstr(subinstr(subinstr(subinstr(st_local("t"), char(96), "'"), char(34), "'"), ",", ";"), char(39), uchar(8217)))
        local ++nnotes
        local nchars = `nchars' + strlen(`"`t'"')
        if regexm(`"`t'"', "[A-Za-z]:\\|/Users/|Dropbox|\.dta|\.do") local ++npath
        file write `N' `""`rel'","dataset note","_dta",`i',"`t'""' _n
    }
    foreach v of varlist _all {
        local nn : char `v'[note0]
        if "`nn'"=="" continue
        forvalues i = 1/`nn' {
            local t : char `v'[note`i']
            mata: st_local("t", subinstr(subinstr(subinstr(subinstr(st_local("t"), char(96), "'"), char(34), "'"), ",", ";"), char(39), uchar(8217)))
            local ++nnotes
            local nchars = `nchars' + strlen(`"`t'"')
            if regexm(`"`t'"', "[A-Za-z]:\\|/Users/|Dropbox|\.dta|\.do") local ++npath
            file write `N' `""`rel'","variable note","`v'",`i',"`t'""' _n
        }
    }
    * ---- characteristics other than notes ----
    local nch = 0
    quietly char list
    local clist : char _dta[]
    foreach c of local clist {
        if regexm("`c'","^note[0-9]*$") continue
        local ++nch
        * reshape/xi leave machine-generated characteristics (__XijVarLab..., __xi__...): label them
        local ckind "dataset characteristic"
        if regexm("`c'","^(__|ReS_|_TS|_lang|_dta)") local ckind "dataset characteristic (machine-generated by reshape/xi/tsset)"
        local t : char _dta[`c']
        mata: st_local("t", subinstr(subinstr(subinstr(subinstr(st_local("t"), char(96), "'"), char(34), "'"), ",", ";"), char(39), uchar(8217)))
        if regexm(`"`t'"', "[A-Za-z]:\\|/Users/|Dropbox|\.dta|\.do") local ++npath
        file write `N' `""`rel'","`ckind'","`c'",,"`t'""' _n
    }
    * ---- variable labels with a direct-identifier term or a path ----
    local nvl = 0
    foreach v of varlist _all {
        local l : variable label `v'
        mata: st_local("l", subinstr(subinstr(subinstr(subinstr(st_local("l"), char(96), "'"), char(34), "'"), ",", ";"), char(39), uchar(8217)))
        local ll = strlower(`"`l'"')
        if regexm("`ll'","(^|[^a-z])(`DIRECT')") local ++nvl
        if regexm(`"`l'"', "[A-Za-z]:\\|/Users/|Dropbox|\.dta") local ++npath
    }
    * ---- value labels: sets, entries, flagged entries ----
    local nsets = 0
    local nent = 0
    local nflag = 0
    quietly label dir
    local sets `r(names)'
    foreach s of local sets {
        local ++nsets
        quietly label list `s'
        local k = r(k)
        local nent = `nent' + `k'
        * walk the entries through Mata (labels may hold quotes)
        mata: _surf_vlabel_m("`s'")
        local nflag = `nflag' + `vlflag'
        forvalues j = 1/`vlflag' {
            file write `L' `""`rel'","`s'",`vlval`j'',"`vltxt`j''","`vlwhy`j''""' _n
        }
    }
    file write `S' `""`rel'","`dlab'",`nv',`ns',`nnotes',`nchars',`nch',`nsets',`nent',`nflag',`nvl',`npath'"' _n
    file read IN line
}
file close IN
file close `S'
file close `N'
file close `L'
di as txt "04b done"
